### ISSUE TITLE
implement integration tests in the toolbox

### ISSUE THREAD

**Issue by vinferrer** [SPiN-Lab/connPFM#37]
### Summary
We shoudl start to implement integration tests for the different functions in the toolbox. This can be divided in different PRs for each part of the toolbox.

### Next Steps
I propose to divide the integration testing in 3 jobs one for each part of the toolbox:

1. pfm integration that calculates the AUC and one surrogate AUC
2. ev integration 
3. debiasing integration

This way we can paralelize the testing and reduce tha amount of clacs in pfm integration without needing to reduce the number of surrogates for the other pipeplines. Thoughts?

**Comment by eurunuela** [comment]
I think dividing the integration tests into 3 makes sense.

**Comment by vinferrer** [comment]
It seems like with the proper ajustments it only takes 5 min to do the integration, look at #38
