### ISSUE TITLE
Calculate thresholds independently for each surrogate

### ISSUE THREAD

**Issue by eurunuela** [SPiN-Lab/connPFM#53]
### Summary

When the edge-time matrices are too big, the histogram of the ETS of all surrogates cannot fit into memory. We could instead calculate the percentiles independently for each of the surrogates and then average them.

### Next Steps
- Add an if statement that calculates the histogram of all surrogates at once only when the size of the ETS matrix isn't too big.
- Write a function that calculates the threshold for one surrogate only.
- Parallelize the calculation of the single surrogate thresholds.

**Comment by CesarCaballeroGaudes** [comment]
Rather than average them, I would save an array of the percentiles (let's say above 90% in steps of 0.1) so that we can produce different summary metrics (average, median, max/min, etc).

**Comment by eurunuela** [comment]
> Rather than average them, I would save an array of the percentiles (let's say above 90% in steps of 0.1) so that we can produce different summary metrics (average, median, max/min, etc).

I've just [committed some changes](https://github.com/SPiN-Lab/connPFM/pull/54/commits/b08c18e96c4087952be2a472d0f4ffb44825c378) that consider this.

The `surrogates_histogram()` function has two modes now:

1. Histograms of all surrogates are concatenated when the matrix isn't too big and the percentile is calculated from there.
2. The percentile is calculated individually for each surrogate and the function then returns the average and the entire array of values in case we want to use other metrics.

**Comment by eurunuela** [comment]
As per #63, we have come up with a more efficient way of calculating the thresholds. We are going to sum the histograms and calculate the percentile on that sum.
