### ISSUE TITLE
Missing tests for multi-echo data

### ISSUE THREAD

**Issue by eurunuela** [SPiN-Lab/connPFM#69]
### Summary
#67 introduces support for multi-echo data. We should add at least an integration test to make sure that the multi-echo pipeline works. We should also add tests for the reading and saving functions.

### Next Steps

- Find light multi-echo data for testing.
- Add one integration test for multi-echo data.
- Add unit tests for the reading and saving functions in `io.py`.

**Comment by vinferrer** [comment]
https://openneuro.org/datasets/ds000258/versions/1.0.0

**Comment by vinferrer** [comment]
Could we use this? https://github.com/ME-ICA/tedana/tree/main/tedana/tests/data

**Comment by vinferrer** [comment]
The issue is that we don have a map in that space
