### ISSUE TITLE
Bold ets part is not neccesary anymore

### ISSUE THREAD

**Issue by vinferrer** [SPiN-Lab/connPFM#94]
### Summary
We were calculating the Edge centric matrix in the original bold signal at the beginning but I think right now this is completely optional. 

### Additional Detail
https://github.com/SPiN-Lab/connPFM/blob/d2d20f60bf21fdfbc03cde63f71fc6ab5c7608da/connPFM/connectivity/ev.py#L176

### Next Steps
Should we comment this part of the code or make it optional?

**Comment by vinferrer** [comment]
What do you think? @eurunuela

**Comment by eurunuela** [comment]
I would remove it actually. We want to use the edge time matrix to select the points for the debiasing step, and for that the BOLD matrix is useless.

**Comment by vinferrer** [comment]
Agreed
